### PR TITLE
Proper implementation of ACCESS-OM3 SPD

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
This now builds and install the OM3 executables and is aware of the different variants.

### CODE REVIEW

**Comment by CodeGat** [comment]
Apologies on the failing syntax check, it is an issue with the syntax checking action, rather than your code! It should still be fine to merge with approval.

**Comment by micaeljtoliveira** [comment]
This has successfully been used to install and run OM3 on gadi using the COSIMA spack instance.

**Comment by aidanheerdegen** [comment]
Neat!

(This is not a review)

**Review by harshula — APPROVED** [review]

**Comment by harshula** [comment]
Thanks!

**Pull request merged**
