### PR TITLE
Add optimisation_report variant

### PR DESCRIPTION
**Pull request by harshula**
I spoke with @penguian, these flags were not intended to be enabled by default.

### CODE REVIEW

**Comment by harshula** [comment]
This PR is only to add the optimisation_report variant. The compiler flag clean-up will happen elsewhere.

### Testing

`7z4fl7a oasis3-mct@master~deterministic~optimisation_report build_system=makefile`
```
         ./configure MPIFC="mpifort" FC="mpifort" CC="mpicc" FCFLAGS="-fp-model precise -fp-model source -align all -g3 -O2 -axCORE-AVX2 -debug all -check none -traceback -ip" \
```

`3hluvm3 oasis3-mct@master~deterministic+optimisation_report build_system=makefile`
```
         ./configure MPIFC="mpifort" FC="mpifort" CC="mpicc" FCFLAGS="-fp-model precise -fp-model source -align all -g3 -O2 -axCORE-AVX2 -debug all -check none -traceback -qopt-report=5 -qopt-report-annotate -ip" \
```

`7skxgsi libaccessom2@master~deterministic~ipo~optimisation_report build_system=cmake build_type=Release generator=make`
```
 '-DDETERMINISTIC:BOOL=OFF' '-DOPTIMISATION_REPORT:BOOL=OFF' '/tmp/root/spack-stage/spack-stage-libaccessom2-master-7skxgsihfps2xbyldwed62q4aofkbysr/spack-src'
```

`pmin3eg libaccessom2@master~deterministic~ipo+optimisation_report build_system=cmake build_type=Release generator=make`
```
'-DDETERMINISTIC:BOOL=OFF' '-DOPTIMISATION_REPORT:BOOL=ON' '/tmp/root/spack-stage/spack-stage-libaccessom2-master-pmin3egme26lj242eyeypqnyqh4lpixw/spack-src'
```

`vc7x3l7 mom5@master~deterministic~optimisation_report build_system=makefile`
```
# grep optimization mom5-master-vc7x3l76iwgurpjgf2yb72cj6eozgf4c/.spack/spack-build-out.txt | wc
      0       0       0
```

`pbac27t mom5@master~deterministic+optimisation_report build_system=makefile`
```
ifort: remark #10397: optimization reports are generated in *.optrpt files in the output location
...
A list of the files you checked out is in the file /tmp/root/spack-stage/spack-stage-mom5-master-pbac27tzzeer4mwducnv4r3ogkifwjaz/spack-src/exp/path_names
```

`m7wmrtf cice5@master~deterministic~optimisation_report build_system=makefile`
```
# grep optimization cice5-master-m7wmrtf33abgs3bcrqgdbbi7awmwf5hh/.spack/spack-build-out.txt | wc
      0       0       0
```

`zw7jrm6 cice5@master~deterministic+optimisation_report build_system=makefile`
```
ifort: remark #10397: optimization reports are generated in *.optrpt files in the output location
cpp -P -traditional [...] -I/tmp/root/spack-stage/spack-stage-cice5-master-zw7jrm6zcmvonrhsnjithgmnrstpf7fv/spack-src/drivers/auscom
```

**Review by CodeGat — APPROVED** [review]
Looks good to me. What does the `REPORT` env var do in mom5?

**Comment by harshula** [comment]
> What does the `REPORT` env var do in mom5?

`bin/mkmf.template.nci`:
```
CFLAGS_REPORT := -qopt-report=5 -qopt-report-annotate
...
ifneq ($(REPORT),)
CFLAGS += $(CFLAGS_REPORT)
FFLAGS += $(FFLAGS_REPORT)
endif
```

**Comment by harshula** [comment]
**Notes**

Using `ifort` there was no significant compile time difference between using the `-qopt-report=5 -qopt-report-annotate` flags and not using it.

**Pull request merged**
